In [1]:
import numpy as np

In [2]:
#fix memory for random
np.random.seed(0)

In [3]:
x1=np.random.randint(10,size=(2,3))

In [4]:
x2=np.random.randint(10,size=6)

In [5]:
x1

array([[5, 0, 3],
       [3, 7, 9]], dtype=int32)

In [6]:
x2

array([3, 5, 2, 4, 7, 6], dtype=int32)

In [7]:
x3=np.random.randint(10,size=(3,2,4))
x3

array([[[8, 8, 1, 6],
        [7, 7, 8, 1]],

       [[5, 9, 8, 9],
        [4, 3, 0, 3]],

       [[5, 0, 2, 3],
        [8, 1, 3, 3]]], dtype=int32)

In [8]:
x1.ndim

2

In [9]:
x1.shape

(2, 3)

In [10]:
x1.size

6

x1.nbytes

In [11]:
x3.nbytes

96

In [12]:
#for defind a number in array directly
x1[-1]

array([3, 7, 9], dtype=int32)

In [13]:
#for defind a number in array directly
x1[[0],[-1]]

array([3], dtype=int32)

In [14]:
#for add numbers according to number of arrang function
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])