import library

In [3]:
import numpy as np

In [4]:
x=[1,2,3,4,5,6,7,8,9]

In [5]:
x[5:-2]

[6, 7]

In [11]:
x[5:-1]

[6, 7, 8]

In [20]:
x1=np.random.randint(10,size=(3,3))

In [23]:
x.reshape(1,3)

AttributeError: 'list' object has no attribute 'reshape'

In [22]:
x1

array([[9, 2, 5],
       [4, 9, 6],
       [4, 0, 8]], dtype=int32)

In [24]:
x1[np.newaxis,:]

array([[[9, 2, 5]]], dtype=int32)

In [27]:
x1[np.newaxis,:0]

array([], shape=(1, 0, 3), dtype=int32)

In [29]:
x=[1,2,3]

In [30]:
y=[3,2,1]

In [31]:
np.concatenate([x,y],axis=0)

array([1, 2, 3, 3, 2, 1])

In [33]:
np.concatenate([x,y],axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [35]:
grid=np.array([1,2,3],[4,5,6])

SyntaxError: invalid syntax (327614096.py, line 1)

In [37]:
a=np.arange(3)

In [38]:
b=np.arange(3)[:,np.newaxis]

In [39]:
print(a)

[0 1 2]


In [40]:
print(b)

[[0]
 [1]
 [2]]


In [41]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [42]:
c=b[:,np.newaxis]

In [43]:
print(a.shape)

(3,)


In [44]:
print(c.shape)

(3, 1, 1)


In [45]:
print(c)

[[[0]]

 [[1]]

 [[2]]]


In [46]:
print(b.shape)

(3, 1)


In [52]:
M=np.ones((2,3))

In [48]:
print(M)

[[1. 1. 1.]
 [1. 1. 1.]]


In [49]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [55]:
d=a.reshape((3,1))
print(d)

[[0]
 [1]
 [2]]


In [54]:
d.shape

(3, 1)

In [62]:
M1=np.ones((3,2))
print(M1)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [63]:
a1=np.arange(3)
print(a1)

[0 1 2]


In [61]:
M1+a1

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [64]:
M1.shape

(3, 2)

In [65]:
a1.shape

(3,)

In [70]:
a1=a1.reshape(3,1)
print(a1)

[[0]
 [1]
 [2]]


In [71]:
M1+a1

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

# pandas library

In [74]:
import pandas as pd

In [76]:
data=[{'a':i,'b':2*i}for i in range(3)]

In [77]:
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [78]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [83]:
data.loc[0,1]

AttributeError: 'list' object has no attribute 'loc'